// login ➡️ Admin user
POST http://localhost:3333/api/users/login HTTP/1.1
Content-type: application/json

{
    "email": "test_admin@dottraining.com",
    "password": "AdminPassword123"
}

// login ➡️ student user
###
POST http://localhost:3333/api/users/login HTTP/1.1
Content-type: application/json

{
    "email": "test_aprendiz@dottraining.com",
    "password": "AprendizPassword789"
}

//login ➡️ correct data but nonexisting user in DB
###
POST http://localhost:3333/api/users/login HTTP/1.1
Content-type: application/json

{
    "email": "ZZZZ@nondottraining.com",
    "password": "nonzzzAprendiz123"
}